import { Router, type IRouter } from "express";
import healthRouter from "./health.ts";
import authRouter from "./auth.ts";
import sessionRouter from "./session.ts";
import emailAuthRouter from "./emailAuth.ts";
import settingsRouter from "./settings.ts";
import usersRouter from "./users.ts";
import gamesRouter from "./games.ts";
import opentdbRouter from "./opentdb.ts";
import geminiRouter from "./gemini.ts";
import questionsRouter from "./questions.ts";
import playRouter from "./play.ts";
import resultsRouter from "./results.ts";
import statsRouter from "./stats.ts";
import ownerRouter from "./owner.ts";

const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(sessionRouter);
router.use(emailAuthRouter);
router.use(settingsRouter);
router.use(usersRouter);
router.use(gamesRouter);
router.use(opentdbRouter);
router.use(geminiRouter);
router.use(questionsRouter);
router.use(playRouter);
router.use(resultsRouter);
router.use(statsRouter);
router.use(ownerRouter);

export default router;
