// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/host-dashboard/Redesign.tsx": () => import("../components/mockups/host-dashboard/Redesign.tsx"),
  "./components/mockups/trivia-gate/ClubNight.tsx": () => import("../components/mockups/trivia-gate/ClubNight.tsx"),
  "./components/mockups/trivia-gate/ElectricStage.tsx": () => import("../components/mockups/trivia-gate/ElectricStage.tsx")
};
